
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 07 07:54:26 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 25;
  public static final int LTE = 32;
  public static final int LBRACKET = 44;
  public static final int EQUALITY = 27;
  public static final int CONST = 6;
  public static final int CHAR = 20;
  public static final int NAMESPACE = 17;
  public static final int LPAREN = 42;
  public static final int SEMI = 38;
  public static final int CONTINUE = 14;
  public static final int DECR = 37;
  public static final int INCR = 36;
  public static final int FOR = 15;
  public static final int MINUS = 23;
  public static final int RPAREN = 43;
  public static final int STATIC = 16;
  public static final int AND = 33;
  public static final int LT = 31;
  public static final int OR = 34;
  public static final int COMMA = 40;
  public static final int BOOL = 21;
  public static final int THICKARROW = 48;
  public static final int CLASS = 4;
  public static final int PLUS = 22;
  public static final int MULTIPLY = 24;
  public static final int IF = 7;
  public static final int DOT = 41;
  public static final int INEQUALITY = 28;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int RBRACKET = 45;
  public static final int EQUAL = 35;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int NUMBER = 18;
  public static final int BREAK = 3;
  public static final int IDENT = 19;
  public static final int VOID = 12;
  public static final int GTE = 30;
  public static final int COLON = 39;
  public static final int LBRACE = 46;
  public static final int ELSE = 5;
  public static final int READ = 10;
  public static final int RBRACE = 47;
  public static final int MODULUS = 26;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int GT = 29;
  public static final int PRINT = 9;
}

