/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class filter_Filter */

#ifndef _Included_filter_Filter
#define _Included_filter_Filter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     filter_Filter
 * Method:    getParticipationsDeserialized
 * Signature: ([Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_filter_Filter_getParticipationsDeserialized
  (JNIEnv *, jobject, jobjectArray, jint, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
